### ISSUE TITLE
Замечания по работе 5.1

### ISSUE THREAD

**Issue by AndriiLitvin** [vityayka/vityayka.github.io#5]
Визуально все норм. Но код чутка над подправить.
1) поменяй местами классы  header и wrapper и закрой блок
2) добавь еще один блок в контент с класом wrapper
в общем сделай два блока хедер и контент
wrapper розкомить ширину
так просто при широком экране не будет улетать вправо  менюшка

**Comment by vityayka** [comment]
Пофиксил кароч.

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ. 
Но кнопки всегда лучше делать не картинками а верстать)

**Comment by AndriiLitvin** [comment]
http://joxi.ru/p277aN5sQkx127
все эти элементы на макете нужно сверстать, картинкой не кайфово делать.

**Comment by vityayka** [comment]
Сверстал.

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
только делай в дальнейшем  структуру папок нормальную чтоб зашел в папку с работой и все быстро нашел. 
/fonts
/css либо style
/images
/js или scripts
