### ISSUE TITLE
Замечания по работе 5.2

### ISSUE THREAD

**Issue by AndriiLitvin** [vityayka/vityayka.github.io#6]
http://joxi.ru/gmvgpyqt5Ya52a
1)Квадрат
2)тут белый фон

**Comment by vityayka** [comment]
Квадрат пофиксил, внизу белый фон сделал. Правда, не совсем идеально: для этого пришлось бы ещё на 4 части разбить одну ячейку, и вышло бы красиво, с сохранением всех пропорций, но сколько тупого кода для этого нужно написать... В общем, примите, пожалуйста, как есть :)

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
