### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [vityayka/vityayka.github.io#8]
у тебя не правильно поставлены условия экранов в медиаквери.
320-479(макет 320), 480-767(макет 480), 768-959(макет 768), 960
на тех экранах по которым есть макеты должна быть пиксельная точность. и должна быть резина для других экранов

**Comment by vityayka** [comment]
Не вижу неправильные условия у себя, я же через max-width задаю состояния свойств, вот и получаются соответственно 4 состояния - до  480рх, до 768рх, до 960рх, больше 960рх (который без #media). Проверьте, всё правильно работает у меня при изменении ширины экрана. Пиксельную точность сделаю, не вопрос.

**Comment by AndriiLitvin** [comment]
да вроде нормально отрабатывает. глянул на css  и не проверил. извиняюсь. просто в большинстве случаев когда я смотрел такой код и проверял было не правильно.

**Comment by AndriiLitvin** [comment]
экран 480 а макет 320 http://joxi.ru/LmGD9PEuRROXx2 вот через что я смотрел https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc

+кнопка меню не такая. там просто надпись.

Экран 960 http://joxi.ru/Dr8ERJ6FkkqRlm макет 768
в условии убери один пиксель до 479 до 767 до 959 и 960

**Comment by vityayka** [comment]
Готово!

**Comment by AndriiLitvin** [comment]
странно ведет себя менюшка http://joxi.ru/Vm67Z8QsxxobR2 если менюшка закрыта но наводишь на область которая на скрине откривается менюшка. хотя должно быть что открывается только при наведении на текст HOME. 

http://joxi.ru/gmvgpyqtxxOQk2 -отцентрируй

**Comment by vityayka** [comment]
Готово!

**Comment by AndriiLitvin** [comment]
Экран 960 http://joxi.ru/l2Z64PNu8wOR02 - сделай либо отступ и стрелку перемести влево чтоб не залазила на текст
и что то маловато у тебя семантических тегов html5. пересмотри по возможности подобавляй. просто вместо div

**Comment by vityayka** [comment]
Готово! Давайте уже к javascript приступать, я уже 2 домашки сделал.

**Comment by vityayka** [comment]
О, а они уже зачтены, вот это прикол! :D

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
